### PR TITLE
Resolves #222: Fixes a bug in HttpClient construction

### LINKED ISSUE #222: Broken Basic Auth in version 1.6.9+
Starting from version 1.6.9 basic-authorization is broken when downloading files.
[This](https://github.com/maven-download-plugin/maven-download-plugin/blob/master/src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java#L202) filed is always null(this.credentialsProvider) because it is only [set](https://github.com/maven-download-plugin/maven-download-plugin/blob/master/src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java#L176) if HttpFileRequester.Builder.proxyHost is not [null](https://github.com/maven-download-plugin/maven-download-plugin/blob/master/src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java#L162)

Example config:
```xml
<plugin>
    <groupId>com.googlecode.maven-download-plugin</groupId>
    <artifactId>download-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>download</id>
            <phase>prepare-package</phase>
            <goals>
                <goal>wget</goal>
            </goals>
            <configuration>
                <url>${url}</url>
                <unpack>true</unpack>
                <outputDirectory>${download-directory}</outputDirectory>
                <serverId>${artifactory-server-id}</serverId>
                <skipCache>true</skipCache>
            </configuration>
        </execution>
    </executions>
</plugin>
```

### PR DESCRIPTION
**Pull request by ajarmoniuk**
fixes https://github.com/maven-download-plugin/maven-download-plugin/issues/222

Basic authentication was not done properly. Fixing that.

Additionally, adding new property: preemptiveAuth, false by default, which lets the user use preemptive authentication if needed.

@longtimeago please review

### CODE REVIEW

File: src/test/java/com/googlecode/download/maven/plugin/internal/HttpFileRequesterTest.java [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+    private Path outputDirectory;
+    private WireMockServer wireMock;
+
+    private final static Random RND = new Random();
+
+    @Before
+    public void setUp() throws Exception {
+        wireMock = new WireMockServer(RND.nextInt(0x7000) + 0x1000);
+        wireMock.start();
+        outputDirectory = Files.createTempDirectory("http-file-requester-test-");
```
Comment (longtimeago) [inline src/test/java/com/googlecode/download/maven/plugin/internal/HttpFileRequesterTest.java:48]: @ajarmoniuk could we use `org.junit.rules.TemporaryFolder` `@Rule` instead?

File: src/test/java/com/googlecode/download/maven/plugin/test/TestUtils.java [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+
+    /**
+     * Copies the {@code src} directory to {@code dst} recursively,
+     * creating the missing directories if necessary
+     *
+     * @param src source directory path
+     * @param dst destination directory path
+     * @throws IOException should an I/O error occur
+     */
+    public static void copyDir(Path src, Path dst) throws IOException {
```
Comment (longtimeago) [inline src/test/java/com/googlecode/download/maven/plugin/test/TestUtils.java:50]: @ajarmoniuk looks unused

**Review by longtimeago — APPROVED** [review]
@ajarmoniuk Looks good, thanks for the contribution!
Please, see 2 suggestions below.

Also, it would be really nice to create a issue describing the problem you are fixing in this PR :)

**Comment by ajarmoniuk** [comment]
> Also, it would be really nice to create a issue describing the problem you are fixing in this PR in more details :)

The issue is #222, it's described in detail, with a test POM.

File: src/test/java/com/googlecode/download/maven/plugin/internal/WGetTest.java [hunk 3]
```diff
@@ -53,37 +52,22 @@
...
     private Path cacheDirectory;
-
     private final static String OUTPUT_FILE_NAME = "output-file";
     private Path outputDirectory;
 
     @Before
     public void setUp() throws Exception {
-        cacheDirectory = Files.createTempDirectory("wget-test-cache-");
-        outputDirectory = Files.createTempDirectory("wget-test-");
+        temporaryFolder.create();
```
Comment (longtimeago) [inline src/test/java/com/googlecode/download/maven/plugin/internal/WGetTest.java:63]: @ajarmoniuk you don't really need to create or delete it. JUnit does it for you automatically

Comment (ajarmoniuk) [reply src/test/java/com/googlecode/download/maven/plugin/internal/WGetTest.java:63]: > @ajarmoniuk you don't really need to create or delete it. JUnit does it for you automatically

Uhhh, not really:

```
[main] INFO org.eclipse.jetty.server.Server - Started @1478ms

java.lang.IllegalStateException: the temporary folder has not yet been created

	at org.junit.rules.TemporaryFolder.getRoot(TemporaryFolder.java:299)
	at com.googlecode.download.maven.plugin.internal.HttpFileRequesterTest.setUp(HttpFileRequesterTest.java:48)
	at junit.framework.TestCase.runBare(TestCase.java:140)
```

I actually assumed that as well in the beginning, and added the explicit creation and destruction afterwards.

Comment (ajarmoniuk) [reply src/test/java/com/googlecode/download/maven/plugin/internal/WGetTest.java:63]: Ahh, because we're using a Junit3 test case, which is caused by extending `AbstractMojoTestCase`.

Comment (ajarmoniuk) [reply src/test/java/com/googlecode/download/maven/plugin/internal/WGetTest.java:63]: Now, removed that inheritance which allowed the rule to work.

**Comment by ajarmoniuk** [comment]
Ok, now it's more concise with those rules.

**Comment by longtimeago** [comment]
@ajarmoniuk awesome, thanks a lot!
