### PR TITLE
Resolves #238: Handling download failures

### LINKED ISSUE #238: Non-200 HTTP status doesn't fail the build
The plugin seems to not check HTTP status code. It masks real problem in bigger projects when something else breaks few steps after the download.

Sample project:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.mycompany.app</groupId>
    <artifactId>my-app</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.googlecode.maven-download-plugin</groupId>
                <artifactId>download-maven-plugin</artifactId>
                <version>1.6.8</version>

                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>wget</goal>
                        </goals>

                        <configuration>
                            <uri>https://httpstat.us/403</uri>
                            <outputDirectory>/tmp</outputDirectory>
                            <failOnError>true</failOnError>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

Console output:
```
$ mvn package   
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< com.mycompany.app:my-app >----------------------
[INFO] Building my-app 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ my-app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /private/tmp/empty-maven-project/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ my-app ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ my-app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /private/tmp/empty-maven-project/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ my-app ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ my-app ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ my-app ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] 
[INFO] --- download-maven-plugin:1.6.8:wget (default) @ my-app ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.021 s
[INFO] Finished at: 2023-04-05T09:53:30+02:00
[INFO] ------------------------------------------------------------------------
```

Everything seems fine, but https://httpstat.us/403 always returns 403 Forbidden, so the authentication failed, so how can build be called successful?

### PR DESCRIPTION
**Pull request by ajarmoniuk**
This PR causes the plugin to fail (unless `failOnError` is `false`) upon a failed download attempt. With errors which can be transient, like 500, it's honoring the `retries` setting.

@longtimeago please check

### CODE REVIEW

File: src/main/java/com/googlecode/download/maven/plugin/internal/DownloadFailureException.java [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+     * @return the HTTP status code.
+     */
+    public int getHttpCode() {
+        return statusCode;
+    }
+
+    /**
+     * @return the HTTP status line.
+     */
+    public String getStatusLine() {
```
Comment (longtimeago) [inline src/main/java/com/googlecode/download/maven/plugin/internal/DownloadFailureException.java:23]: @ajarmoniuk seems unused

File: src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java [hunk 2]
```diff
@@ -384,25 +384,34 @@ public void execute() throws MojoExecutionException, MojoFailureException {
...
+                        } else {
+                            if (this.failOnError) {
+                                throw new MojoExecutionException(ex.getMessage(), ex);
+                            } else {
+                                getLog().warn(ex.getMessage());
+                            }
+                        }
                     } catch (IOException ex) {
                         getLog().warn("Could not get content", ex);
-                        this.retries--;
```
Comment (longtimeago) [inline src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java:395]: @ajarmoniuk don't we need to fail on IOException if `this.failOnError == true` ?

File: src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java [hunk 3]
```diff
@@ -384,25 +384,34 @@ public void execute() throws MojoExecutionException, MojoFailureException {
...
+
                 boolean done = false;
-                while (!done && this.retries > 0) {
+                for (int retriesLeft = this.retries; !done && retriesLeft > 0; --retriesLeft) {
                     try {
                         this.doGet(outputFile);
                         checksums.validate(outputFile);
                         done = true;
+                    } catch (DownloadFailureException ex) {
+
```
Comment (longtimeago) [inline src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java:395]:
```suggestion
```

File: src/test/java/com/googlecode/download/maven/plugin/internal/WGetTest.java [hunk 4]
```diff
@@ -295,24 +318,65 @@ public void testCacheRetainingValuesFromTwoConcurrentCalls() throws Exception {
...
-            @Override
-            protected HttpResponse doSendRequest(HttpRequest request, HttpClientConnection conn, HttpContext context)
-                    throws IOException {
-                HttpResponse response = new BasicHttpResponse(HttpVersion.HTTP_1_1, HttpStatus.SC_OK, "Ok");
-                response.setEntity(new StringEntity(contentSupplier.get() + "\n"));
-                return response;
-            }
-        });
+    /**
+     * Plugin execution should fail if a non-200 code was returned by the resource being downloaded.
```
Comment (longtimeago) [inline src/test/java/com/googlecode/download/maven/plugin/internal/WGetTest.java:322]:
```suggestion
     * Plugin execution should fail if code >= 400 was returned by the resource being downloaded.
```

File: src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java [hunk 5]
```diff
@@ -283,8 +304,11 @@ public void download(final File outputFile, List<Header> headers) throws IOExcep
      * @throws IOException thrown if I/O operations don't succeed
      */
     private Object handleResponse( URI uri, File outputFile, HttpCacheContext clientContext, HttpResponse response )
-            throws IOException
-    {
+            throws IOException, DownloadFailureException {
+        if (response.getStatusLine().getStatusCode() >= 300) {
```
Comment (longtimeago) [inline src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java:308]: @ajarmoniuk shouldn't this be `>= 400` ? Why do we want to fail on 3xx ?

File: src/test/java/com/googlecode/download/maven/plugin/internal/WGetTest.java [hunk 6]
```diff
@@ -295,24 +318,65 @@ public void testCacheRetainingValuesFromTwoConcurrentCalls() throws Exception {
...
+                setVariableValueToObject(m, "uri", URI.create(wireMock.baseUrl()));
+                setVariableValueToObject(m, "skipCache", true);
+                setVariableValueToObject(m, "failOnError", true);
+            }).execute();
+            fail("The mojo should have failed upon error");
+        } catch (Exception e) {
+            assertThat(e, is(instanceOf(MojoExecutionException.class)));
+            assertThat(e.getCause(), is(instanceOf(DownloadFailureException.class)));
+            assertThat(((DownloadFailureException) e.getCause()).getHttpCode(), is(HttpStatus.SC_FORBIDDEN));
+        }
```
Comment (longtimeago) [inline src/test/java/com/googlecode/download/maven/plugin/internal/WGetTest.java:338]: @ajarmoniuk let's check the actual number of retries happened here

File: src/main/java/com/googlecode/download/maven/plugin/internal/DownloadFailureException.java (hunk 1 above)
Comment (ajarmoniuk) [reply src/main/java/com/googlecode/download/maven/plugin/internal/DownloadFailureException.java:23]: Now it's no longer unused :)

File: src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java (hunk 2 above)
Comment (ajarmoniuk) [reply src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java:395]: True. Applied the same treatment that we do for `DownloadFailureException`.

File: src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java (hunk 5 above)
Comment (ajarmoniuk) [reply src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java:308]: Changed to >= 400.

File: src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java [hunk 7]
```diff
@@ -331,22 +331,22 @@ public void execute() throws MojoExecutionException, MojoFailureException {
         this.outputDirectory.mkdirs();
         final File outputFile = new File(this.outputDirectory, this.outputFileName);
         final Lock fileLock = FILE_LOCKS.computeIfAbsent(
-            outputFile.getAbsolutePath(), ignored -> new ReentrantLock()
+                outputFile.getAbsolutePath(), ignored -> new ReentrantLock()
```
[the remark this answers is not in the document]
Comment (ajarmoniuk) [reply src/main/java/com/googlecode/download/maven/plugin/internal/WGetMojo.java:334]: Corrected.

File: src/test/java/com/googlecode/download/maven/plugin/internal/WGetTest.java (hunk 6 above)
Comment (ajarmoniuk) [reply src/test/java/com/googlecode/download/maven/plugin/internal/WGetTest.java:339]: Done.

**Comment by ajarmoniuk** [comment]
On my local machine, some integration tests are failing due to various reasons (e.g. `gmavenplus-plugin` complaining about timestamp operation no longer supported in `alwaysOverwrite`). I'm preparing another PR to deal with that.

File: src/main/java/com/googlecode/download/maven/plugin/internal/DownloadFailureException.java [hunk 8]
```diff
@@ -0,0 +1,41 @@
+package com.googlecode.download.maven.plugin.internal;
+
+/**
+ * Represents a download failure exception, thrown when the requested resource returns
+ * a non-20x HTTP code.
+ */
+public class DownloadFailureException extends Exception {
```
[the remark this answers is not in the document]
Comment (longtimeago) [reply src/main/java/com/googlecode/download/maven/plugin/internal/DownloadFailureException.java:7]: @ajarmoniuk please, address my comment above

File: src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java [hunk 9]
```diff
@@ -283,8 +304,11 @@ public void download(final File outputFile, List<Header> headers) throws IOExcep
      * @throws IOException thrown if I/O operations don't succeed
      */
     private Object handleResponse( URI uri, File outputFile, HttpCacheContext clientContext, HttpResponse response )
-            throws IOException
-    {
+            throws IOException, DownloadFailureException {
+        if (response.getStatusLine().getStatusCode() >= 400) {
+            throw new DownloadFailureException(response.getStatusLine().getStatusCode(),
```
[the remark this answers is not in the document]
Comment (ajarmoniuk) [reply src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java:309]: I think forgot to implement your review comment before resolving the item. The review item should be reopened. Sure, I can do it.

**Review by longtimeago — APPROVED** [review]
@ajarmoniuk awesome, thanks a lot! :+1:
